#### Day4 Concepts
- Continued with Numpy
- Pandas

In [1]:
import numpy as np

In [2]:
............................................................


SyntaxError: invalid syntax (3580036830.py, line 1)

In [3]:
# create 2 random arrays with shape (5,5)
rn=np.random.randint(100,500,25).reshape(5,5)
rn2=np.random.randint(2000,5000,25).reshape(5,5)

In [4]:
#logarithms and exponentials
np.log(1)

0.0

In [5]:
np.log2(2)

1.0

In [6]:
np.log10(1)

0.0

In [7]:
np.log(rn)

array([[6.19440539, 6.08677473, 6.16961073, 5.90808294, 4.97673374],
       [5.51342875, 6.01615716, 5.49306144, 6.01859321, 6.13772705],
       [4.65396035, 4.72738782, 5.68017261, 5.26269019, 5.31811999],
       [4.78749174, 5.70044357, 4.94164242, 5.09986643, 5.90263333],
       [5.24702407, 5.83188248, 4.91998093, 5.95583737, 6.20050917]])

In [8]:
np.log(rn2)

array([[8.1056094 , 8.2839993 , 8.48858793, 7.90654723, 8.40827078],
       [7.81075812, 8.13973228, 8.34450508, 8.37562963, 8.12533509],
       [8.45489217, 8.43228868, 7.68845536, 8.28349413, 8.20166019],
       [7.88193749, 8.07121854, 8.00869818, 8.35819746, 7.69802917],
       [7.63964229, 8.37262974, 8.46421427, 7.92588032, 8.20849175]])

In [11]:
np.exp(2),np.exp(1)

(7.38905609893065, 2.718281828459045)

In [12]:
np.exp(rn)

array([[6.37229881e+212, 1.22905704e+191, 3.91527571e+207,
        6.61255566e+159, 9.39074129e+062],
       [5.07027496e+107, 1.15010524e+178, 3.41632440e+105,
        3.12631016e+178, 1.19769192e+201],
       [3.98951957e+045, 1.18925902e+049, 1.77126360e+127,
        6.58923516e+083, 3.94524800e+088],
       [1.30418088e+052, 7.14578737e+129, 6.32743171e+060,
        1.67608111e+071, 8.94912093e+158],
       [3.28058702e+082, 1.24284889e+148, 3.15024275e+059,
        4.34180200e+167, 1.27991043e+214]])

In [13]:
np.exp(rn2)

C:\Users\ruthu\AppData\Local\Temp\ipykernel_17864\1532026422.py:1: RuntimeWarning: overflow encountered in exp
  np.exp(rn2)


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

##### Broad casting
- a big change/difference
- applying a scalar on the array

In [14]:
rn+5

array([[495, 445, 483, 373, 150],
       [253, 415, 248, 416, 468],
       [110, 118, 298, 198, 209],
       [125, 304, 145, 169, 371],
       [195, 346, 142, 391, 498]])

#### Numpy Vectorized function

In [18]:
#greater fun which compare 2 integers
def greater(a,b):
    if a>b:
        return a
    elif a==b:
        return False
    else:return b
    
greater(9,8),greater(10,15),greater(5,5)

(9, 15, False)

In [19]:
greater([9,4,5],[8,1,6])
# [9,4,5]
# [9,4,6]

[9, 4, 5]

In [22]:
v=np.vectorize(greater)
v([9,4,5],[8,1,6])

array([9, 4, 6])

In [23]:
help(np.vectorize)

Help on class vectorize in module numpy:

class vectorize(builtins.object)
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False, signature=None)
 |  
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False,
 |            signature=None)
 |  
 |  Generalized function class.
 |  
 |  Define a vectorized function which takes a nested sequence of objects or
 |  numpy arrays as inputs and returns a single numpy array or a tuple of numpy
 |  arrays. The vectorized function evaluates `pyfunc` over successive tuples
 |  of the input arrays like the python map function, except it uses the
 |  broadcasting rules of numpy.
 |  
 |  The data type of the output of `vectorized` is determined by calling
 |  the function with the first element of the input.  This can be avoided
 |  by specifying the `otypes` argument.
 |  
 |  Parameters
 |  ----------
 |  pyfunc : callable
 |      A python function or method.
 |  otypes : str or list of dtypes, optional
 |      The 

In [24]:
import pandas as pd

In [25]:
pd.__version__

'1.4.4'

#### pandas
- One of the most efficient data science modules used to work with data
- Pandas stands for PanelData
- It has 2 data structures
    1. Series and
        - Sequential data can be arranged either side by side or line by line
        - pd.Series(data/objects)
    2. DataFrame
        - Data can be organized in the form of table
        - pd.DataFrame(objects)
        
- This module helps the user to perform
    1. Data Analysis
    2. Data Manipulation and
    3. Data Cleaning
        - all the above together called as Data Pre-processing

In [27]:
# working with pandas.Series(data)
print(pd.Series("Vignans Nirula"))
pd.Series(range(1,11))

0    Vignans Nirula
dtype: object


0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [28]:
#apply the Series on tuple,list,dict,nd arrays of all types
l=[1,2,3,4]
pd.Series(l)

0    1
1    2
2    3
3    4
dtype: int64

In [29]:
s=("A","vyshu","B")
pd.Series(s)

0        A
1    vyshu
2        B
dtype: object

In [30]:
d={1:"a",2:"b",3:"c"}
pd.Series(d)

1    a
2    b
3    c
dtype: object

In [31]:
#with arrays
import numpy as np

In [33]:
print(pd.Series(np.arange(21,30)))

0    21
1    22
2    23
3    24
4    25
5    26
6    27
7    28
8    29
dtype: int32


In [38]:
s=pd.Series(np.random.randint(20,50,10),
           index=[v for v in range(100,110)])
s

100    26
101    36
102    35
103    31
104    22
105    38
106    33
107    31
108    20
109    34
dtype: int32

In [39]:
s.shape

(10,)

In [41]:
s.index[2]#

102

In [43]:
s.values[2]

35

In [44]:
s._values[2]

35

In [45]:
s[102]

35

100 to 109-->

In [46]:
#Data Frame
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__deprecated_num_index_names', '__dir__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_is_numpy_dev', '_libs', '_testing', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat

In [47]:
help(pd.array)

Help on function array in module pandas.core.construction:

array(data: 'Sequence[object] | AnyArrayLike', dtype: 'Dtype | None' = None, copy: 'bool' = True) -> 'ExtensionArray'
    Create an array.
    
    Parameters
    ----------
    data : Sequence of objects
        The scalars inside `data` should be instances of the
        scalar type for `dtype`. It's expected that `data`
        represents a 1-dimensional array of data.
    
        When `data` is an Index or Series, the underlying array
        will be extracted from `data`.
    
    dtype : str, np.dtype, or ExtensionDtype, optional
        The dtype to use for the array. This may be a NumPy
        dtype or an extension type registered with pandas using
        :meth:`pandas.api.extensions.register_extension_dtype`.
    
        If not specified, there are two possibilities:
    
        1. When `data` is a :class:`Series`, :class:`Index`, or
           :class:`ExtensionArray`, the `dtype` will be taken
           from th

In [52]:
print(pd.array([4,5,6,10],dtype=str))

<PandasArray>
['4', '5', '6', '10']
Length: 4, dtype: str64


In [55]:
pd.array((5,6,7,9)) # allows tupl&list only

<IntegerArray>
[5, 6, 7, 9]
Length: 4, dtype: Int64

In [56]:
pd.array({8,3,4,5,10}) # raised to Error

TypeError: object cannot be converted to an IntegerDtype

In [57]:
np.array({4,5,6,9})

array({9, 4, 5, 6}, dtype=object)

In [58]:
help(pd.arrays)

Help on package pandas.arrays in pandas:

NAME
    pandas.arrays - All of pandas' ExtensionArrays.

DESCRIPTION
    See :ref:`extending.extension-types` for more.

PACKAGE CONTENTS


CLASSES
    pandas._libs.interval.IntervalMixin(builtins.object)
        pandas.core.arrays.interval.IntervalArray(pandas._libs.interval.IntervalMixin, pandas.core.arrays.base.ExtensionArray)
    pandas.core.arraylike.OpsMixin(builtins.object)
        pandas.core.arrays.numpy_.PandasArray(pandas.core.arraylike.OpsMixin, pandas.core.arrays._mixins.NDArrayBackedExtensionArray, pandas.core.strings.object_array.ObjectStringArrayMixin)
            pandas.core.arrays.string_.StringArray(pandas.core.arrays.string_.BaseStringArray, pandas.core.arrays.numpy_.PandasArray)
        pandas.core.arrays.sparse.array.SparseArray(pandas.core.arraylike.OpsMixin, pandas.core.base.PandasObject, pandas.core.arrays.base.ExtensionArray)
        pandas.core.arrays.string_arrow.ArrowStringArray(pandas.core.arraylike.OpsMixin, pand

In [61]:
pd.array(['hi','hello',None,'student'])

<StringArray>
['hi', 'hello', <NA>, 'student']
Length: 4, dtype: string

In [62]:
pd.array(['hi','hello',None,'student',True])

<PandasArray>
['hi', 'hello', None, 'student', True]
Length: 5, dtype: object

In [64]:
#pd.Series(pd.array())
pd.Series(pd.array([2,3,4,5,6,None]))

0       2
1       3
2       4
3       5
4       6
5    <NA>
dtype: Int64

In [74]:
#pd.DataFrame -->2d structure
dates=pd.date_range('10-02-2022','20-02-2022',periods=10)
temp=[v for v in np.random.randint(30,40,10)]
pd.Series(temp,index=dates)

2022-10-02 00:00:00    33
2022-09-07 02:40:00    38
2022-08-13 05:20:00    39
2022-07-19 08:00:00    33
2022-06-24 10:40:00    33
2022-05-30 13:20:00    30
2022-05-05 16:00:00    35
2022-04-10 18:40:00    39
2022-03-16 21:20:00    30
2022-02-20 00:00:00    33
dtype: int32

In [76]:
dt=pd.date_range(start='1/1/2024',periods=10)
pd.Series(temp,index=dt)

2024-01-01    33
2024-01-02    38
2024-01-03    39
2024-01-04    33
2024-01-05    33
2024-01-06    30
2024-01-07    35
2024-01-08    39
2024-01-09    30
2024-01-10    33
Freq: D, dtype: int32

In [77]:
# rows and columns
pd.DataFrame(np.arange(20,30))

0
0  20
1  21
2  22
3  23
4  24
5  25
6  26
7  27
8  28
9  29

In [78]:
help(pd.DataFrame)

Help on class DataFrame in module pandas.core.frame:

class DataFrame(pandas.core.generic.NDFrame, pandas.core.arraylike.OpsMixin)
 |  DataFrame(data=None, index: 'Axes | None' = None, columns: 'Axes | None' = None, dtype: 'Dtype | None' = None, copy: 'bool | None' = None)
 |  
 |  Two-dimensional, size-mutable, potentially heterogeneous tabular data.
 |  
 |  Data structure also contains labeled axes (rows and columns).
 |  Arithmetic operations align on both row and column labels. Can be
 |  thought of as a dict-like container for Series objects. The primary
 |  pandas data structure.
 |  
 |  Parameters
 |  ----------
 |  data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
 |      Dict can contain Series, arrays, constants, dataclass or list-like objects. If
 |      data is a dict, column order follows insertion-order. If a dict contains Series
 |      which have an index defined, it is aligned by its index.
 |  
 |      .. versionchanged:: 0.25.0
 |         If 

In [82]:
# try with dict
# col-->header:keys
dic={'C1':(1,2,3),'C2':[4,5,6]}
df=pd.DataFrame(dic,index=['R1','R2','R3'])
df

C1  C2
R1   1   4
R2   2   5
R3   3   6

In [83]:
df.shape

(3, 2)

In [84]:
df.columns

Index(['C1', 'C2'], dtype='object')

In [90]:
# create the dataframe of student info of 5
# Name Roll Branch GPA (4,5)
dic={'Name':('Swetha','Jyothi','Ramijun','Pravallika','Nandini'),
    'Roll':(503,502,553,511,509),
    'Branch':('CSE','IT','ECE','CSE','CSE'),
    'GPA':(8.9,9.0,8.89,8.5,9.0)}
std=pd.DataFrame(dic,index=['R1','R2','R3','R4','R5'])
std

Name  Roll Branch   GPA
R1      Swetha   503    CSE  8.90
R2      Jyothi   502     IT  9.00
R3     Ramijun   553    ECE  8.89
R4  Pravallika   511    CSE  8.50
R5     Nandini   509    CSE  9.00

#### Accessing the DF 
- as series and as dataframe 

In [92]:
# DataFrame depends upon the columns
std['Roll'] # as a series

R1    503
R2    502
R3    553
R4    511
R5    509
Name: Roll, dtype: int64

In [93]:
std[['Name']] # as a df

Name
R1      Swetha
R2      Jyothi
R3     Ramijun
R4  Pravallika
R5     Nandini

In [94]:
std.Branch

R1    CSE
R2     IT
R3    ECE
R4    CSE
R5    CSE
Name: Branch, dtype: object

In [96]:
std[['Name','GPA']] # AS A DF

Name   GPA
R1      Swetha  8.90
R2      Jyothi  9.00
R3     Ramijun  8.89
R4  Pravallika  8.50
R5     Nandini  9.00

In [97]:
std[::]

Name  Roll Branch   GPA
R1      Swetha   503    CSE  8.90
R2      Jyothi   502     IT  9.00
R3     Ramijun   553    ECE  8.89
R4  Pravallika   511    CSE  8.50
R5     Nandini   509    CSE  9.00

In [98]:
std['Name'].iloc[3:]

R4    Pravallika
R5       Nandini
Name: Name, dtype: object

In [100]:
# all the header
# 3 rows
std[:].iloc[:3]

Name  Roll Branch   GPA
R1   Swetha   503    CSE  8.90
R2   Jyothi   502     IT  9.00
R3  Ramijun   553    ECE  8.89

In [101]:
# point the single value in the DF
std

Name  Roll Branch   GPA
R1      Swetha   503    CSE  8.90
R2      Jyothi   502     IT  9.00
R3     Ramijun   553    ECE  8.89
R4  Pravallika   511    CSE  8.50
R5     Nandini   509    CSE  9.00

In [102]:
std[:].iloc[2][1]

553

In [103]:
std['Roll'][2]

553

In [104]:
std.info

<bound method DataFrame.info of           Name  Roll Branch   GPA
R1      Swetha   503    CSE  8.90
R2      Jyothi   502     IT  9.00
R3     Ramijun   553    ECE  8.89
R4  Pravallika   511    CSE  8.50
R5     Nandini   509    CSE  9.00>

In [105]:
std.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, R1 to R5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    5 non-null      object 
 1   Roll    5 non-null      int64  
 2   Branch  5 non-null      object 
 3   GPA     5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 372.0+ bytes


In [106]:
std.describe() # statistics of the dataset

Roll      GPA
count    5.000000  5.00000
mean   515.600000  8.85800
std     21.255588  0.20693
min    502.000000  8.50000
25%    503.000000  8.89000
50%    509.000000  8.90000
75%    511.000000  9.00000
max    553.000000  9.00000

In [107]:
std

Name  Roll Branch   GPA
R1      Swetha   503    CSE  8.90
R2      Jyothi   502     IT  9.00
R3     Ramijun   553    ECE  8.89
R4  Pravallika   511    CSE  8.50
R5     Nandini   509    CSE  9.00

In [108]:
std.Name.value_counts

<bound method IndexOpsMixin.value_counts of R1        Swetha
R2        Jyothi
R3       Ramijun
R4    Pravallika
R5       Nandini
Name: Name, dtype: object>

In [109]:
std['Roll'].value_counts

<bound method IndexOpsMixin.value_counts of R1    503
R2    502
R3    553
R4    511
R5    509
Name: Roll, dtype: int64>

In [110]:
std.GPA.min()

8.5

In [111]:
std.Roll.max()

553

In [112]:
# take another df
# apply --> join,merge,concat()


In [114]:
# create the dataframe of student info of 5
# Name Roll Branch GPA (4,5)
d={'Name':('Swetha','Jyothi','Ramya','Pravallika','Nandini'),
    'Roll':(503,502,505,511,509),
    'Branch':('CSE','IT','CSM','CSE','CSE'),
    'GPA':(8.9,9.0,8.89,7.4,9.0)}
std_df=pd.DataFrame(d,index=['R1','R2','R3','R4','R5'])
std_df

Name  Roll Branch   GPA
R1      Swetha   503    CSE  8.90
R2      Jyothi   502     IT  9.00
R3       Ramya   505    CSM  8.89
R4  Pravallika   511    CSE  7.40
R5     Nandini   509    CSE  9.00

In [115]:
std.merge(std_df)

Name  Roll Branch  GPA
0   Swetha   503    CSE  8.9
1   Jyothi   502     IT  9.0
2  Nandini   509    CSE  9.0

In [118]:
std.join((std_df)) # columns overlap

ValueError: columns overlap but no suffix specified: Index(['Name', 'Roll', 'Branch', 'GPA'], dtype='object')

In [122]:
# 2 different dfs
df1=pd.DataFrame({'f':(1,2,3),'s':[4,5,6]})
df2=pd.DataFrame({'t':[20,45,67],'fr':(90,45,67)})
comb=df1.join(df2)
comb.index=[1,2,3]
comb

f  s   t  fr
1  1  4  20  90
2  2  5  45  45
3  3  6  67  67

In [124]:
pd.concat([df1,df2])

f    s     t    fr
0  1.0  4.0   NaN   NaN
1  2.0  5.0   NaN   NaN
2  3.0  6.0   NaN   NaN
0  NaN  NaN  20.0  90.0
1  NaN  NaN  45.0  45.0
2  NaN  NaN  67.0  67.0

In [125]:
"rupa"+"k"

'rupak'

In [128]:
df1+df2

f  fr   s   t
0 NaN NaN NaN NaN
1 NaN NaN NaN NaN
2 NaN NaN NaN NaN

In [129]:
df1-->f,s there is no data for t,fr(NaN)
df2-->t,fr(NaN) and no data for f,s

SyntaxError: invalid syntax (400894435.py, line 1)

#### working with .csv file

In [130]:
import pandas as pd

In [131]:
marks_df=pd.read_csv("marks.csv")
marks_df

Name  Roll  Dept  Year  Python  Java
0      Bhavya   548   CSE     3      24    24
1   Chandrika   542    IT     3      18    20
2     Deepika   695   CSE     1      15    25
3     Fathima   523   ECE     3      15    15
4        Asha   569   CSM     3      17    24
5     Jahnavi   566  CSDS     2      15    23
6       Kavya   574    IT     2      18    16
7     Nirmala   587   CSM     4      16    25
8     Lavanya   650  CSDS     1      23    22
9     Sridhar   617   CSE     4      17    23
10    Vaibhav   670   ECE     1      15    20
11    Sandhya   529    IT     4      18    19
12    Pallavi   595   CSE     1      21    16
13     Anusha   684    IT     2      23    16
14     Ravali   631   CSE     1      20    15

In [132]:
type(marks_df)

pandas.core.frame.DataFrame

In [133]:
#adding extra column
marks_df['DS']=[v for v in np.random.randint(50,100,15)]

In [137]:
marks_df.index=[chr(v) for v in range(65,80)]
marks_df

Name  Roll  Dept  Year  Python  Java  DS
A     Bhavya   548   CSE     3      24    24  97
B  Chandrika   542    IT     3      18    20  58
C    Deepika   695   CSE     1      15    25  58
D    Fathima   523   ECE     3      15    15  93
E       Asha   569   CSM     3      17    24  65
F    Jahnavi   566  CSDS     2      15    23  73
G      Kavya   574    IT     2      18    16  50
H    Nirmala   587   CSM     4      16    25  61
I    Lavanya   650  CSDS     1      23    22  52
J    Sridhar   617   CSE     4      17    23  77
K    Vaibhav   670   ECE     1      15    20  75
L    Sandhya   529    IT     4      18    19  61
M    Pallavi   595   CSE     1      21    16  56
N     Anusha   684    IT     2      23    16  80
O     Ravali   631   CSE     1      20    15  94

In [136]:
for val in range(65,80):
    print(chr(val),end=" ")

A B C D E F G H I J K L M N O 

In [138]:
marks_df.sort_values('Java')

Name  Roll  Dept  Year  Python  Java  DS
D    Fathima   523   ECE     3      15    15  93
O     Ravali   631   CSE     1      20    15  94
G      Kavya   574    IT     2      18    16  50
M    Pallavi   595   CSE     1      21    16  56
N     Anusha   684    IT     2      23    16  80
L    Sandhya   529    IT     4      18    19  61
B  Chandrika   542    IT     3      18    20  58
K    Vaibhav   670   ECE     1      15    20  75
I    Lavanya   650  CSDS     1      23    22  52
F    Jahnavi   566  CSDS     2      15    23  73
J    Sridhar   617   CSE     4      17    23  77
A     Bhavya   548   CSE     3      24    24  97
E       Asha   569   CSM     3      17    24  65
C    Deepika   695   CSE     1      15    25  58
H    Nirmala   587   CSM     4      16    25  61

In [140]:
marks_df.sort_values('Python',ascending=False)

Name  Roll  Dept  Year  Python  Java  DS
A     Bhavya   548   CSE     3      24    24  97
I    Lavanya   650  CSDS     1      23    22  52
N     Anusha   684    IT     2      23    16  80
M    Pallavi   595   CSE     1      21    16  56
O     Ravali   631   CSE     1      20    15  94
B  Chandrika   542    IT     3      18    20  58
G      Kavya   574    IT     2      18    16  50
L    Sandhya   529    IT     4      18    19  61
E       Asha   569   CSM     3      17    24  65
J    Sridhar   617   CSE     4      17    23  77
H    Nirmala   587   CSM     4      16    25  61
C    Deepika   695   CSE     1      15    25  58
D    Fathima   523   ECE     3      15    15  93
F    Jahnavi   566  CSDS     2      15    23  73
K    Vaibhav   670   ECE     1      15    20  75

In [141]:
marks_df

Name  Roll  Dept  Year  Python  Java  DS
A     Bhavya   548   CSE     3      24    24  97
B  Chandrika   542    IT     3      18    20  58
C    Deepika   695   CSE     1      15    25  58
D    Fathima   523   ECE     3      15    15  93
E       Asha   569   CSM     3      17    24  65
F    Jahnavi   566  CSDS     2      15    23  73
G      Kavya   574    IT     2      18    16  50
H    Nirmala   587   CSM     4      16    25  61
I    Lavanya   650  CSDS     1      23    22  52
J    Sridhar   617   CSE     4      17    23  77
K    Vaibhav   670   ECE     1      15    20  75
L    Sandhya   529    IT     4      18    19  61
M    Pallavi   595   CSE     1      21    16  56
N     Anusha   684    IT     2      23    16  80
O     Ravali   631   CSE     1      20    15  94

In [143]:
# generates any random sample
marks_df.sample()

Name  Roll Dept  Year  Python  Java  DS
M  Pallavi   595  CSE     1      21    16  56

In [144]:
marks_df.sample(3) # n random samples

Name  Roll Dept  Year  Python  Java  DS
E     Asha   569  CSM     3      17    24  65
M  Pallavi   595  CSE     1      21    16  56
J  Sridhar   617  CSE     4      17    23  77

In [145]:
# FIRST 5 samples of dataset bydefault
marks_df.head() # 

Name  Roll Dept  Year  Python  Java  DS
A     Bhavya   548  CSE     3      24    24  97
B  Chandrika   542   IT     3      18    20  58
C    Deepika   695  CSE     1      15    25  58
D    Fathima   523  ECE     3      15    15  93
E       Asha   569  CSM     3      17    24  65

In [146]:
marks_df.head(2)

Name  Roll Dept  Year  Python  Java  DS
A     Bhavya   548  CSE     3      24    24  97
B  Chandrika   542   IT     3      18    20  58

In [147]:
marks_df.tail() # last 5 samples

Name  Roll Dept  Year  Python  Java  DS
K  Vaibhav   670  ECE     1      15    20  75
L  Sandhya   529   IT     4      18    19  61
M  Pallavi   595  CSE     1      21    16  56
N   Anusha   684   IT     2      23    16  80
O   Ravali   631  CSE     1      20    15  94

In [148]:
marks_df.tail(3)

Name  Roll Dept  Year  Python  Java  DS
M  Pallavi   595  CSE     1      21    16  56
N   Anusha   684   IT     2      23    16  80
O   Ravali   631  CSE     1      20    15  94

In [149]:
marks_df.Roll.sum()

8980

In [152]:
marks_df[['Python','Java','DS']].sum()

Python     275
Java       303
DS        1050
dtype: int64

In [154]:
marks_df.Python.sum()

275

In [155]:
#add the total columns=total(python,java,ds)

A    121
B     76
C     73
D    108
E     82
F     88
G     68
H     77
I     75
J     94
K     90
L     79
M     77
N    103
O    114
dtype: int64

In [157]:
marks_df

Name  Roll  Dept  Year  Python  Java  DS
A     Bhavya   548   CSE     3      24    24  97
B  Chandrika   542    IT     3      18    20  58
C    Deepika   695   CSE     1      15    25  58
D    Fathima   523   ECE     3      15    15  93
E       Asha   569   CSM     3      17    24  65
F    Jahnavi   566  CSDS     2      15    23  73
G      Kavya   574    IT     2      18    16  50
H    Nirmala   587   CSM     4      16    25  61
I    Lavanya   650  CSDS     1      23    22  52
J    Sridhar   617   CSE     4      17    23  77
K    Vaibhav   670   ECE     1      15    20  75
L    Sandhya   529    IT     4      18    19  61
M    Pallavi   595   CSE     1      21    16  56
N     Anusha   684    IT     2      23    16  80
O     Ravali   631   CSE     1      20    15  94

In [159]:
marks_df['Total']=marks_df[['Python','Java','DS']].sum(axis=1)
marks_df

Name  Roll  Dept  Year  Python  Java  DS  Total
A     Bhavya   548   CSE     3      24    24  97    145
B  Chandrika   542    IT     3      18    20  58     96
C    Deepika   695   CSE     1      15    25  58     98
D    Fathima   523   ECE     3      15    15  93    123
E       Asha   569   CSM     3      17    24  65    106
F    Jahnavi   566  CSDS     2      15    23  73    111
G      Kavya   574    IT     2      18    16  50     84
H    Nirmala   587   CSM     4      16    25  61    102
I    Lavanya   650  CSDS     1      23    22  52     97
J    Sridhar   617   CSE     4      17    23  77    117
K    Vaibhav   670   ECE     1      15    20  75    110
L    Sandhya   529    IT     4      18    19  61     98
M    Pallavi   595   CSE     1      21    16  56     93
N     Anusha   684    IT     2      23    16  80    119
O     Ravali   631   CSE     1      20    15  94    129

In [160]:
# Data Cleaning means removal of Null(NaN) data in the dataset
marks_df.isnull()

Name   Roll   Dept   Year  Python   Java     DS  Total
A  False  False  False  False   False  False  False  False
B  False  False  False  False   False  False  False  False
C  False  False  False  False   False  False  False  False
D  False  False  False  False   False  False  False  False
E  False  False  False  False   False  False  False  False
F  False  False  False  False   False  False  False  False
G  False  False  False  False   False  False  False  False
H  False  False  False  False   False  False  False  False
I  False  False  False  False   False  False  False  False
J  False  False  False  False   False  False  False  False
K  False  False  False  False   False  False  False  False
L  False  False  False  False   False  False  False  False
M  False  False  False  False   False  False  False  False
N  False  False  False  False   False  False  False  False
O  False  False  False  False   False  False  False  False

In [161]:
marks_df.isna()

Name   Roll   Dept   Year  Python   Java     DS  Total
A  False  False  False  False   False  False  False  False
B  False  False  False  False   False  False  False  False
C  False  False  False  False   False  False  False  False
D  False  False  False  False   False  False  False  False
E  False  False  False  False   False  False  False  False
F  False  False  False  False   False  False  False  False
G  False  False  False  False   False  False  False  False
H  False  False  False  False   False  False  False  False
I  False  False  False  False   False  False  False  False
J  False  False  False  False   False  False  False  False
K  False  False  False  False   False  False  False  False
L  False  False  False  False   False  False  False  False
M  False  False  False  False   False  False  False  False
N  False  False  False  False   False  False  False  False
O  False  False  False  False   False  False  False  False

In [162]:
new=pd.read_csv("marks.csv")
new

Name   Roll  Dept  Year  Python  Java
0      Bhavya  525.0   CSE   3.0    16.0  17.0
1   Chandrika  588.0    IT   3.0    17.0  25.0
2     Deepika    NaN   CSE   1.0    18.0   NaN
3     Fathima  599.0   ECE   NaN    19.0  23.0
4        Asha  578.0   CSM   1.0    25.0  19.0
5     Jahnavi  613.0  CSDS   4.0    17.0  15.0
6       Kavya  539.0    IT   2.0     NaN  17.0
7     Nirmala    NaN   CSM   3.0    16.0   NaN
8     Lavanya  539.0  CSDS   4.0    23.0  24.0
9     Sridhar  510.0   CSE   NaN    21.0  20.0
10    Vaibhav  652.0   NaN   1.0    25.0   NaN
11    Sandhya    NaN    IT   3.0    15.0  18.0
12    Pallavi  617.0   CSE   4.0    18.0  20.0
13     Anusha  543.0    IT   2.0     NaN  25.0
14     Ravali  692.0   CSE   3.0    25.0  25.0

In [163]:
new.isna()

Name   Roll   Dept   Year  Python   Java
0   False  False  False  False   False  False
1   False  False  False  False   False  False
2   False   True  False  False   False   True
3   False  False  False   True   False  False
4   False  False  False  False   False  False
5   False  False  False  False   False  False
6   False  False  False  False    True  False
7   False   True  False  False   False   True
8   False  False  False  False   False  False
9   False  False  False   True   False  False
10  False  False   True  False   False   True
11  False   True  False  False   False  False
12  False  False  False  False   False  False
13  False  False  False  False    True  False
14  False  False  False  False   False  False

In [165]:
update=new.dropna()
update

Name   Roll  Dept  Year  Python  Java
0      Bhavya  525.0   CSE   3.0    16.0  17.0
1   Chandrika  588.0    IT   3.0    17.0  25.0
4        Asha  578.0   CSM   1.0    25.0  19.0
5     Jahnavi  613.0  CSDS   4.0    17.0  15.0
8     Lavanya  539.0  CSDS   4.0    23.0  24.0
12    Pallavi  617.0   CSE   4.0    18.0  20.0
14     Ravali  692.0   CSE   3.0    25.0  25.0

In [169]:
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__deprecated_num_index_names', '__dir__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_is_numpy_dev', '_libs', '_testing', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat

In [177]:
from datasets import iris

ModuleNotFoundError: No module named 'datasets'